

- name: Initialize registration process
  uri: url="{{_r_acmedns_api}}/register" method=POST return_content=yes body_format=json status_code=201
  register: reg_result

- name: create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- debug: var=reg_result.json

- template:
    src: config.fact.j2
    dest: "{{_r_acmesh_regconfig}}"
  vars:
    res: "{{reg_result.json}}"
    _facts_dict:
      fulldomain: "{{res.fulldomain}}"
      password: "{{res.password}}"
      subdomain: "{{res.subdomain}}"
      username: "{{res.username}}"

- name: re-read facts after adding custom fact
  setup: filter=ansible_local

- debug: var=ansible_local